### ISSUE TITLE
Exclude Gemfile.lock.

### ISSUE THREAD

**Issue by frederikhors** [toshimaru/rubocop-rails_config#6]
Using VSCode and this plugin everything works except this:

```yaml
AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - Gemfile.lock
```

Why?
